apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: ghcr.io/ramoswilly/frontend-app:placeholder
        imagePullPolicy: Always # Siempre busca la última versión
        ports:
        - containerPort: 80
